; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.6.0 on Thu Aug 21 2025 09:00:53 GMT-0700 (Pacific Daylight Time)

G92 Z0 ; set Z=0
M118 L1 P0 S"Warning: Z is NOT homed but its position has been set to 0."
