; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.6.0 on Thu Aug 21 2025 09:00:53 GMT-0700 (Pacific Daylight Time)
; modified by Cohen Weston on August 22, 2025


; Used to re-home Z axis if a new part is used with a different height
M291 P"Jog Z to your MACHINE Z reference (tool setter/table touch-off). Click OK when ready." S3
G92 Z0                          ; current position = machine Z0