; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool v3.6.0 on Thu Aug 21 2025 09:00:53 GMT-0700 (Pacific Daylight Time)

G92 Y0 ; set Y=0
M118 L1 P0 S"Warning: Y is NOT homed but its position has been set to 0."
