; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool v3.6.0 on Thu Aug 21 2025 09:00:53 GMT-0700 (Pacific Daylight Time)

G92 X0 ; set X=0
M118 L1 P0 S"Warning: X is NOT homed but its position has been set to 0."
