; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.6.0 on Thu Aug 21 2025 09:00:53 GMT-0700 (Pacific Daylight Time)

M116 P0 ; wait for tool temperatures to be reached
