; homez.g
; does nothing
;
; generated by RepRapFirmware Configuration Tool v3.6.0 on Thu Aug 21 2025 09:00:53 GMT-0700 (Pacific Daylight Time)
; modified by Cohen Weston on August 22, 2025

M291 P"This button is useless. Use Home All to home the axes." S3
